name: Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore CheckMods.slnx

      - name: Test
        run: dotnet test CheckMods.slnx --no-restore --verbosity normal
